name: Build the ESP‑IDF Project

on:
  push:
    tags:
      - 'v*'

permissions:           
  contents: write       
  packages: write   
     
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: 'recursive'
    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.1
        target: esp32
        path: '.'
    - name: Upload firmware binaries
      uses: actions/upload-artifact@v4
      with:
        name: esp32-firmware
        path: |
          build/*.bin
          build/*.elf
          build/*.map
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}      
        name: Release ${{ github.ref_name }}
        files: |
          build/*.bin
          build/*.elf
          build/*.map
        make_latest: true                     
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Checkout latest release tag
      run: |
        LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
        git checkout $LATEST_TAG