name: Build the ESP‑IDF Project

on:
  push:
    tags:
      - 'v*'

permissions:           
  contents: write       
  packages: write   
     
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: 'recursive'
    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.1
        target: esp32
        path: '.'
    - name: Upload firmware binaries
      uses: actions/upload-artifact@v4
      with:
        name: esp32-firmware
        path: |
          build/*.bin
          build/*.elf
          build/*.map
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}      
        name: Release ${{ github.ref_name }}
        files: |
          build/*.bin
          build/*.elf
          build/*.map
        make_latest: true                     
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Run latest-tag
      uses: EndBug/latest-tag@latest
      with:
        # You can change the name of the tag or branch with this input.
        # Default: 'latest'

        # If a description is provided, the action will use it to create an annotated tag. If none is given, the action will create a lightweight tag.
        # Default: ''
        description: Latest release

        # Force-update a branch instead of using a tag.
        # Default: false

        # Directory to use when executing git commands
        # Default: '${{ github.workspace }}'
